# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pril.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(421, 595)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet("background: #333; /* Цвет фона */\n"
"    color: #fc0; /* Цвет текста */\n"
"\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(10, 470, 401, 81))
        self.Start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Start.setMouseTracking(False)
        self.Start.setStyleSheet("")
        self.Start.setObjectName("Start")
        self.progressBarLod = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarLod.setGeometry(QtCore.QRect(10, 440, 401, 23))
        self.progressBarLod.setStyleSheet("")
        self.progressBarLod.setProperty("value", 0)
        self.progressBarLod.setObjectName("progressBarLod")
        self.infoLoading = QtWidgets.QLabel(self.centralwidget)
        self.infoLoading.setGeometry(QtCore.QRect(190, 385, 221, 41))
        self.infoLoading.setIndent(10)
        self.infoLoading.setObjectName("infoLoading")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(180, 270, 20, 161))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textPass = QtWidgets.QTextEdit(self.centralwidget)
        self.textPass.setGeometry(QtCore.QRect(120, 170, 181, 21))
        self.textPass.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textPass.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textPass.setObjectName("textPass")
        self.textLogin = QtWidgets.QTextEdit(self.centralwidget)
        self.textLogin.setGeometry(QtCore.QRect(120, 140, 181, 21))
        self.textLogin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textLogin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textLogin.setObjectName("textLogin")
        self.Dannie = QtWidgets.QLabel(self.centralwidget)
        self.Dannie.setGeometry(QtCore.QRect(120, 120, 181, 16))
        self.Dannie.setIndent(1)
        self.Dannie.setObjectName("Dannie")
        self.ButPOTVERD = QtWidgets.QPushButton(self.centralwidget)
        self.ButPOTVERD.setGeometry(QtCore.QRect(120, 220, 181, 23))
        self.ButPOTVERD.setStyleSheet("")
        self.ButPOTVERD.setObjectName("ButPOTVERD")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 131, 16))
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 260, 431, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 171, 31))
        self.label_4.setObjectName("label_4")
        self.gal1 = QtWidgets.QCheckBox(self.centralwidget)
        self.gal1.setGeometry(QtCore.QRect(10, 300, 171, 21))
        self.gal1.setObjectName("gal1")
        self.gal2 = QtWidgets.QCheckBox(self.centralwidget)
        self.gal2.setGeometry(QtCore.QRect(10, 320, 171, 21))
        self.gal2.setObjectName("gal2")
        self.gal3 = QtWidgets.QCheckBox(self.centralwidget)
        self.gal3.setGeometry(QtCore.QRect(10, 340, 171, 21))
        self.gal3.setObjectName("gal3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 361, 431, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(120, 200, 181, 17))
        self.radioButton.setObjectName("radioButton")
        self.generation = QtWidgets.QPushButton(self.centralwidget)
        self.generation.setGeometry(QtCore.QRect(200, 350, 211, 16))
        self.generation.setObjectName("generation")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 275, 211, 21))
        self.label_2.setObjectName("label_2")
        self.randomkay = QtWidgets.QTextBrowser(self.centralwidget)
        self.randomkay.setGeometry(QtCore.QRect(200, 300, 211, 21))
        self.randomkay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.randomkay.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.randomkay.setObjectName("randomkay")
        self.gal4 = QtWidgets.QCheckBox(self.centralwidget)
        self.gal4.setGeometry(QtCore.QRect(200, 330, 191, 16))
        self.gal4.setObjectName("gal4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(130, 300, 51, 51))
        self.frame.setStyleSheet("background-image: url(\"D:/nedohaker/icons8-steam-48.png\")")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 130, 101, 101))
        self.frame_2.setStyleSheet("background-image: url(\"D:/nedohaker/icons8-hack-100.png\")")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(310, 130, 101, 101))
        self.frame_3.setStyleSheet("background-image: url(\"D:/nedohaker/icons8-hack-100.png\")")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(-80, -40, 511, 161))
        self.frame_4.setStyleSheet("background-image: url(\"D:/nedohaker/image (1).png\")")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.nacrutka = QtWidgets.QTextEdit(self.centralwidget)
        self.nacrutka.setGeometry(QtCore.QRect(10, 380, 171, 21))
        self.nacrutka.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.nacrutka.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.nacrutka.setObjectName("nacrutka")
        self.butnak = QtWidgets.QPushButton(self.centralwidget)
        self.butnak.setGeometry(QtCore.QRect(10, 410, 171, 20))
        self.butnak.setObjectName("butnak")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start.setText(_translate("MainWindow", "Начать"))
        self.infoLoading.setText(_translate("MainWindow", "Нет ответа"))
        self.textPass.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Password</p></body></html>"))
        self.textLogin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Login</p></body></html>"))
        self.Dannie.setText(_translate("MainWindow", "Введите данные аккаунта Steam"))
        self.ButPOTVERD.setText(_translate("MainWindow", "Потвердить"))
        self.label.setText(_translate("MainWindow", "Создатель TRIBUT"))
        self.label_4.setText(_translate("MainWindow", "BETA функции "))
        self.gal1.setText(_translate("MainWindow", "Тихая накрутка"))
        self.gal2.setText(_translate("MainWindow", "Снятие Vac BAN"))
        self.gal3.setText(_translate("MainWindow", "Смена валюты"))
        self.radioButton.setText(_translate("MainWindow", "Я доверяю этому приложению"))
        self.generation.setText(_translate("MainWindow", "Генерировать"))
        self.label_2.setText(_translate("MainWindow", "Генератор ключей Steam"))
        self.randomkay.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тут пока пусто</p></body></html>"))
        self.gal4.setText(_translate("MainWindow", "Проверять ключ"))
        self.nacrutka.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Введите число для накрутки </p></body></html>"))
        self.butnak.setText(_translate("MainWindow", "подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())




